# -*- coding: utf-8 -*-
"""IRIS_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nll9Mut78MXCQ7LkJ0td2D6KTkFR-Oy4
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/gdrive')
# %cd /gdrive

!ls "/content/drive/My Drive/ALL"

# Commented out IPython magic to ensure Python compatibility.
!pip install ipython-autotime

# %load_ext autotime

from keras.applications.nasnet import NASNetLarge,NASNetMobile
from keras.preprocessing import image
from keras.applications.nasnet import preprocess_input

from keras.applications.resnet import ResNet50,ResNet101,ResNet152
from keras.applications.resnet import preprocess_input

from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import preprocess_input

from keras.applications.vgg19 import VGG19
from keras.applications.vgg19 import preprocess_input

from keras.applications.xception import Xception
from keras.applications.xception import preprocess_input

from keras.applications.inception_v3 import InceptionV3
from keras.applications.inception_v3 import preprocess_input

from keras.applications.inception_resnet_v2 import InceptionResNetV2
from keras.applications.inception_resnet_v2 import preprocess_input

from keras.applications.mobilenet import MobileNet
from keras.applications.mobilenet import preprocess_input

from keras.applications.densenet import DenseNet121,DenseNet169,DenseNet201
from keras.applications.densenet import preprocess_input

from keras.applications.mobilenet_v2 import MobileNetV2
from keras.applications.mobilenet_v2 import preprocess_input

import numpy as np
from keras.applications.nasnet import decode_predictions
from sklearn.metrics.pairwise import cosine_similarity
import cv2
import os
import glob
from sklearn.metrics.pairwise import cosine_similarity

img_dir = "/gdrive/My Drive/ALL" 
data_path = os.path.join(img_dir,'*g')
files = glob.glob(data_path)
data = []

dm=(224,224)
for f1 in files:

  try:
      img = cv2.imread(f1)
      img=cv2.resize(img,dm)
      data.append(img)
  except:
      pass

#data=pd.DataFrame(data)
type(data)

import numpy as np
data=np.array(data)

VGG16_model = VGG16(weights='imagenet',include_top=False,pooling='avg')
features_train=VGG16_model.predict(data)

l=[]
img = cv2.imread('//gdrive//My Drive//ALL//5.jpg')
img=cv2.resize(img,dm)
l.append(img)
l=np.array(l)
f=VGG16_model.predict(l)
result=cosine_similarity(f,features_train)
result=result>0.99999

result

students=dict()
for i in files:
  students[(i.split('/')[-1]).split('.')[0]]="NA"

import pandas as pd

df=pd.DataFrame(list(students.items()),columns=["name","attendance"],index=[i for i in range(1,962)])
df

x=1
for i in result[0]:
  if i:
    df.loc[x,"attendance"]="Present"
    break
  x+=1
print(x)

!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from google.colab import files
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

df.to_excel("/gdrive/My Drive/Attendance/sheet.xlsx")

students

